### PR TITLE
Feat/25 email list

### LINKED ISSUE #23: [FIX] setAllowCredentials true로 인한 origin 명시
## ✨작성할 기능에 대한 설명을 적어주세요
```
setAllowCredentials true로 인한 origin 명시
```

<br><br>

## ✅ 해야 할 작업들을 작성해주세요
- [x] spring security setAllowCredentials true로 인한 origin 명시

<br><br>

## 🦋 연관된 이슈
-

### LINKED ISSUE #25: [FEAT] Non-Member Email List
## ✨작성할 기능에 대한 설명을 적어주세요
```
Non-Member Email List - admin만 접근가능
Non-Member Email을 입력 시 discord webhook으로 admin에게 알림 전송
```

<br><br>

## ✅ 해야 할 작업들을 작성해주세요
- [x] Non-Member Email List - admin만 접근가능
- [x] Non-Member Email을 입력 시 discord webhook으로 admin에게 알림 전송

<br><br>

## 🦋 연관된 이슈
-

### PR DESCRIPTION
**Pull request by minwoo1999**
## ✨ 요약
```
Non-Member Email List - admin만 접근가능
Non-Member Email을 입력 시 discord webhook으로 admin에게 알림 전송
현우형이 제작해준 EmailTemplate으로 변경완료
Cookie값 전송을 위해 origin * -> origin 명시적으로 지정
Credential true 옵션부여
회원가입 시 nonMember 테이블 state값 변경
```

<br><br>

## 😎 해결한 이슈
- close #25 

<br><br>

### CODE REVIEW

**Comment by minwoo1999** [comment]
### 테스트 커버리지 측정
|File|Coverage [55.34%]|:green_apple:|
|:-|:-:|:-:|
|[MailSenderServiceImpl.java](https://github.com/rework-kr/REWORK-SERVER/blob/11f75da0588b4c3bd0953b1effd9010a8664bcb8/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmail%2Fapplication%2Fimpl%2FMailSenderServiceImpl.java)|85.42%|:green_apple:|
|[NonMemberEmail.java](https://github.com/rework-kr/REWORK-SERVER/blob/11f75da0588b4c3bd0953b1effd9010a8664bcb8/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmember%2Fdomain%2FNonMemberEmail.java)|75%|:green_apple:|
|[MemberServiceImpl.java](https://github.com/rework-kr/REWORK-SERVER/blob/11f75da0588b4c3bd0953b1effd9010a8664bcb8/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmember%2Fapplication%2Fimpl%2FMemberServiceImpl.java)|71.49%|:green_apple:|
|[MemeberRequestDto.java](https://github.com/rework-kr/REWORK-SERVER/blob/11f75da0588b4c3bd0953b1effd9010a8664bcb8/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmember%2Fapplication%2Fdto%2FMemeberRequestDto.java)|70%|:green_apple:|
|[MemberController.java](https://github.com/rework-kr/REWORK-SERVER/blob/11f75da0588b4c3bd0953b1effd9010a8664bcb8/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmember%2Fpresentation%2FMemberController.java)|59.35%|:green_apple:|
|[MemberResponseDto.java](https://github.com/rework-kr/REWORK-SERVER/blob/11f75da0588b4c3bd0953b1effd9010a8664bcb8/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmember%2Fapplication%2Fdto%2FMemberResponseDto.java)|54.03%|:green_apple:|
|[MailSenderController.java](https://github.com/rework-kr/REWORK-SERVER/blob/11f75da0588b4c3bd0953b1effd9010a8664bcb8/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmail%2Fpresentation%2FMailSenderController.java)|25.64%|:x:|
|[MailSenderApi.java](https://github.com/rework-kr/REWORK-SERVER/blob/11f75da0588b4c3bd0953b1effd9010a8664bcb8/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmail%2Finfra%2FMailSenderApi.java)|15.52%|:x:|
|[WebhookService.java](https://github.com/rework-kr/REWORK-SERVER/blob/11f75da0588b4c3bd0953b1effd9010a8664bcb8/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fdiscord%2FWebhookService.java)|3.49%|:x:|

|Total Project Coverage|72.94%|:green_apple:|
|:-|:-:|:-:|

**Comment by minwoo1999** [comment]
### 테스트 커버리지 측정
|File|Coverage [55.78%]|:green_apple:|
|:-|:-:|:-:|
|[MailSenderServiceImpl.java](https://github.com/rework-kr/REWORK-SERVER/blob/08ce5a841172da4797bc3d44014474367fecc685/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmail%2Fapplication%2Fimpl%2FMailSenderServiceImpl.java)|85.42%|:green_apple:|
|[NonMemberEmail.java](https://github.com/rework-kr/REWORK-SERVER/blob/08ce5a841172da4797bc3d44014474367fecc685/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmember%2Fdomain%2FNonMemberEmail.java)|76.47%|:green_apple:|
|[MemberServiceImpl.java](https://github.com/rework-kr/REWORK-SERVER/blob/08ce5a841172da4797bc3d44014474367fecc685/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmember%2Fapplication%2Fimpl%2FMemberServiceImpl.java)|72.54%|:green_apple:|
|[MemeberRequestDto.java](https://github.com/rework-kr/REWORK-SERVER/blob/08ce5a841172da4797bc3d44014474367fecc685/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmember%2Fapplication%2Fdto%2FMemeberRequestDto.java)|70%|:green_apple:|
|[MemberController.java](https://github.com/rework-kr/REWORK-SERVER/blob/08ce5a841172da4797bc3d44014474367fecc685/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmember%2Fpresentation%2FMemberController.java)|59.35%|:green_apple:|
|[MemberResponseDto.java](https://github.com/rework-kr/REWORK-SERVER/blob/08ce5a841172da4797bc3d44014474367fecc685/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmember%2Fapplication%2Fdto%2FMemberResponseDto.java)|54.03%|:green_apple:|
|[MailSenderController.java](https://github.com/rework-kr/REWORK-SERVER/blob/08ce5a841172da4797bc3d44014474367fecc685/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmail%2Fpresentation%2FMailSenderController.java)|25.64%|:x:|
|[MailSenderApi.java](https://github.com/rework-kr/REWORK-SERVER/blob/08ce5a841172da4797bc3d44014474367fecc685/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fmail%2Finfra%2FMailSenderApi.java)|15.52%|:x:|
|[WebhookService.java](https://github.com/rework-kr/REWORK-SERVER/blob/08ce5a841172da4797bc3d44014474367fecc685/src%2Fmain%2Fjava%2Fcom%2Fexample%2Frework%2Fdiscord%2FWebhookService.java)|3.49%|:x:|

|Total Project Coverage|73.01%|:green_apple:|
|:-|:-:|:-:|

**Review by OneK-2 — APPROVED** [review]
고생하셨습니다~
RestTemplate은 처음 봤네요.. 공부해보겠습니다 ㅎㅎ
Test Coverage는 무슨일..?

**Comment by minwoo1999** [comment]
> 고생하셨습니다~ RestTemplate은 처음 봤네요.. 공부해보겠습니다 ㅎㅎ Test Coverage는 무슨일..?

resttemplate이 아마 Spring 3부터 지원된 동기식 REST API로 알고있습니다

형님이 테스트코드를 잘 짜주셔서 ... 70퍼가 넘었네요

**Pull request merged**
